# Form implementation generated from reading ui file 'd:\Workspace\My Projects\epc-combiner-tool\ui\app.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 643)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("* {\n"
"   background-color: #262626;\n"
"   color: #fafafa;\n"
"   font: 14px \'Inter\';\n"
"   border-color: #404040;\n"
"   border-width: 1px;\n"
"}\n"
"\n"
"QPushButton{\n"
"   height: 36px;\n"
"   font-weight: 500;\n"
"   background-color: #fafafa;\n"
"   color:  #171717;\n"
"   border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color: #f5f5f5;\n"
"}\n"
"\n"
"QComboBox{\n"
"   height: 36px;\n"
"   background-color: #171717;\n"
"   color: #fafafa;\n"
"   border: 1px solid #404040;\n"
"   border-radius: 4px;\n"
"   padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"   border: 1px solid #fafafa\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"   background-color: #171717;\n"
"   border: 1px solid #404040;\n"
"   border-radius: 4px;\n"
"   padding: 1.5px 3px;\n"
"   margin-top: 4px;\n"
"}\n"
"\n"
"QListView::item{\n"
"   padding: 2px 4px;\n"
"   height: 24px;\n"
"   border-radius: 4px;\n"
"}\n"
"\n"
"QListView::item:hover{\n"
"   background-color: #404040;\n"
"}\n"
"\n"
"QListView::item:selected{\n"
"   background-color: #404040;\n"
"   color: #fafafa;\n"
"   border: 0px;\n"
"   outline: 0px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"   border: 0px\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"   image: url(./assets/icons/chevron-down.svg);\n"
"   width: 14px;\n"
"   height: 14px;\n"
"   margin-right: 8px;\n"
"}\n"
"\n"
"QListWidget{\n"
"   padding:4px;\n"
"   background-color: #171717\n"
"}\n"
"\n"
"QTableWidget {\n"
"   border: 1px solid #404040;\n"
"   background-color: #171717;\n"
"   gridline-color: #404040;\n"
"   border-radius: 4px;\n"
"   padding: 1px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"   padding: 2px 8px; \n"
"   font-weight: 600;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"   border: none;\n"
"   padding: 2px 8px;\n"
"}\n"
"\n"
"\n"
"QTableWidget QTableHead{\n"
"   font-weight: 600\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"   border: none;\n"
"   background: none;\n"
"   width: 8px;\n"
"   margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"   border: 0px;\n"
"   background: none;\n"
"   height: 8px;\n"
"   margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"   background: #262626;\n"
"   min-height: 20px;\n"
"   border-radius: 9999px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"   background: #262626;\n"
"   min-width: 20px;\n"
"   border-radius: 9999px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"   background: none;\n"
"   border: none;\n"
"   height: 14px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"   background: none;\n"
"   border: none;\n"
"   height: 14px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"   background: none;\n"
"   width: 14px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"   background: none;\n"
"   width: 14px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"   background: none;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"   font-weight: 500;\n"
"   height: 32px;\n"
"   background-color: #171717;\n"
"   border: 0px;\n"
"   border-bottom: 1px solid #404040;\n"
"   border-right: 1px solid #404040;\n"
"}\n"
"\n"
"#reset_btn{\n"
"   background: transparent;\n"
"   border: 1px solid #262626;\n"
"   color: #fafafa\n"
"}\n"
"\n"
"#reset_btn:hover{\n"
"   background-color: #404040;\n"
"}\n"
"\n"
"#tableLayout{\n"
"   border: 1px solid #404040;\n"
"   background-color: #171717\n"
"}\n"
"\n"
"\n"
"#tableLayout *{\n"
"   border-bottom: 1px solid #404040;\n"
"   background-color: #171717\n"
"}\n"
"\n"
"#epcListBox{\n"
"   border: 1px solid #404040;\n"
"   border-radius: 4px;\n"
"   background: #171717;\n"
"}\n"
"\n"
"#epcListBox #epc_list{\n"
"   border: 0px; \n"
"   border-radius: 4px;\n"
"   font-weight: 500\n"
"}\n"
"\n"
"#menu_bar QPushButton{\n"
"    background-color: #ccc;\n"
"    color: #fafafa;\n"
"    border: 1px solid  #404040;\n"
"}\n"
"\n"
"#title_bar{\n"
"    background-color: #171717;\n"
"}\n"
"\n"
"#title_bar Spacer{\n"
"    background: none\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_bar_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.title_bar_2.setStyleSheet("background-color: #171717")
        self.title_bar_2.setObjectName("title_bar_2")
        self.title_bar = QtWidgets.QHBoxLayout(self.title_bar_2)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_13.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_13.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #525252;\n"
"}")
        self.pushButton_13.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/arrow-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_6.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_14.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_14.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #525252;\n"
"}")
        self.pushButton_14.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/arrow-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_6.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_15.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_15.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #525252;\n"
"}")
        self.pushButton_15.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_15.setIcon(icon2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_6.addWidget(self.pushButton_15)
        self.title_bar.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(638, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_bar.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_12.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #525252;\n"
"}")
        self.pushButton_12.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/assets/icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_11.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_11.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #525252;\n"
"}")
        self.pushButton_11.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_10.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #525252;\n"
"}")
        self.pushButton_10.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/minimize-2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.title_bar_2)
        self.pushButton_9.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_9.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #ef4444;\n"
"}")
        self.pushButton_9.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.title_bar.addLayout(self.horizontalLayout_5)
        self.title_bar.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.title_bar_2)
        self.outlet = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.outlet.setObjectName("outlet")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.main_page)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.epc_list_box = QtWidgets.QWidget(parent=self.main_page)
        self.epc_list_box.setObjectName("epc_list_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.epc_list_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.epc_list_box)
        self.pushButton.setStyleSheet("background: none; border: 0px;")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\Workspace\\My Projects\\epc-combiner-tool\\ui\\../assets/icons/tag.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_19 = QtWidgets.QLabel(parent=self.epc_list_box)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet("QLabel{\n"
"    font-size: 24px;\n"
"    font-weight: 500;\n"
"    padding: 0px;\n"
"}")
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setIndent(0)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.epc_list_box)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet("color: #52525b")
        self.label_20.setScaledContents(False)
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setIndent(0)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.listWidget = QtWidgets.QListWidget(parent=self.epc_list_box)
        self.listWidget.setAutoFillBackground(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget)
        self.epc_list_actions = QtWidgets.QHBoxLayout()
        self.epc_list_actions.setSpacing(4)
        self.epc_list_actions.setObjectName("epc_list_actions")
        self.connect_button = QtWidgets.QPushButton(parent=self.epc_list_box)
        self.connect_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.connect_button.setObjectName("connect_button")
        self.epc_list_actions.addWidget(self.connect_button)
        self.reset_button = QtWidgets.QPushButton(parent=self.epc_list_box)
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reset_button.setStyleSheet("background: #fff; border: 1px solid #ccc")
        self.reset_button.setObjectName("reset_button")
        self.epc_list_actions.addWidget(self.reset_button)
        self.verticalLayout_5.addLayout(self.epc_list_actions)
        self.horizontalLayout_3.addWidget(self.epc_list_box)
        self.splitter = QtWidgets.QSplitter(parent=self.main_page)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.order_infor_table = QtWidgets.QTableWidget(parent=self.splitter)
        self.order_infor_table.setAutoFillBackground(True)
        self.order_infor_table.setStyleSheet("")
        self.order_infor_table.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.order_infor_table.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.order_infor_table.setMidLineWidth(1)
        self.order_infor_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.order_infor_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.order_infor_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.order_infor_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.order_infor_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.order_infor_table.setCornerButtonEnabled(True)
        self.order_infor_table.setObjectName("order_infor_table")
        self.order_infor_table.setColumnCount(7)
        self.order_infor_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_infor_table.setItem(1, 6, item)
        self.order_infor_table.horizontalHeader().setMinimumSectionSize(150)
        self.order_infor_table.horizontalHeader().setStretchLastSection(False)
        self.order_infor_table.verticalHeader().setVisible(False)
        self.order_infor_table.verticalHeader().setCascadingSectionResizes(True)
        self.order_infor_table.verticalHeader().setHighlightSections(False)
        self.order_infor_table.verticalHeader().setSortIndicatorShown(False)
        self.order_infor_table.verticalHeader().setStretchLastSection(False)
        self.sizing_table = QtWidgets.QTableWidget(parent=self.splitter)
        self.sizing_table.setColumnCount(3)
        self.sizing_table.setObjectName("sizing_table")
        self.sizing_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sizing_table.setItem(5, 2, item)
        self.sizing_table.horizontalHeader().setVisible(False)
        self.header_top = QtWidgets.QFrame(parent=self.splitter)
        self.header_top.setObjectName("header_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.manu_order_select = QtWidgets.QComboBox(parent=self.header_top)
        self.manu_order_select.setAutoFillBackground(False)
        self.manu_order_select.setEditable(True)
        self.manu_order_select.setObjectName("manu_order_select")
        self.manu_order_select.addItem("")
        self.manu_order_select.addItem("")
        self.horizontalLayout_2.addWidget(self.manu_order_select)
        self.combine_form = QtWidgets.QFrame(parent=self.splitter)
        self.combine_form.setObjectName("combine_form")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.combine_form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.actionSelect = QtWidgets.QComboBox(parent=self.combine_form)
        self.actionSelect.setObjectName("actionSelect")
        self.actionSelect.addItem("")
        self.actionSelect.addItem("")
        self.horizontalLayout.addWidget(self.actionSelect)
        self.size_select = QtWidgets.QComboBox(parent=self.combine_form)
        self.size_select.setAutoFillBackground(False)
        self.size_select.setObjectName("size_select")
        self.size_select.addItem("")
        self.size_select.addItem("")
        self.size_select.addItem("")
        self.horizontalLayout.addWidget(self.size_select)
        self.combine_type_select = QtWidgets.QComboBox(parent=self.combine_form)
        self.combine_type_select.setObjectName("combine_type_select")
        self.combine_type_select.addItem("")
        self.combine_type_select.addItem("")
        self.horizontalLayout.addWidget(self.combine_type_select)
        self.monoSeqSelect = QtWidgets.QComboBox(parent=self.combine_form)
        self.monoSeqSelect.setObjectName("monoSeqSelect")
        self.monoSeqSelect.addItem("")
        self.horizontalLayout.addWidget(self.monoSeqSelect)
        self.combine_proceed_button = QtWidgets.QPushButton(parent=self.combine_form)
        self.combine_proceed_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.combine_proceed_button.setIcon(icon7)
        self.combine_proceed_button.setIconSize(QtCore.QSize(18, 18))
        self.combine_proceed_button.setObjectName("combine_proceed_button")
        self.horizontalLayout.addWidget(self.combine_proceed_button)
        self.horizontalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.outlet.addWidget(self.main_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.widget = QtWidgets.QWidget(parent=self.setting_page)
        self.widget.setGeometry(QtCore.QRect(501, 161, 320, 140))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_6 = QtWidgets.QSplitter(parent=self.widget)
        self.splitter_6.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.label = QtWidgets.QLabel(parent=self.splitter_6)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.splitter_6)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.splitter_6)
        self.splitter_5 = QtWidgets.QSplitter(parent=self.widget)
        self.splitter_5.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.label_3 = QtWidgets.QLabel(parent=self.splitter_5)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.splitter_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.splitter_5)
        self.splitter_7 = QtWidgets.QSplitter(parent=self.widget)
        self.splitter_7.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.splitter_7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.splitter_7)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.splitter_7)
        self.outlet.addWidget(self.setting_page)
        self.verticalLayout_2.addWidget(self.outlet)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionDatabase_connection = QtGui.QAction(parent=MainWindow)
        self.actionDatabase_connection.setObjectName("actionDatabase_connection")
        self.actionMinimize = QtGui.QAction(parent=MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actioncollapse_sidebar = QtGui.QAction(parent=MainWindow)
        self.actioncollapse_sidebar.setCheckable(True)
        self.actioncollapse_sidebar.setChecked(True)
        self.actioncollapse_sidebar.setObjectName("actioncollapse_sidebar")

        self.retranslateUi(MainWindow)
        self.outlet.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "1000"))
        self.label_20.setText(_translate("MainWindow", "Tem đã quét"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "30340C10084E714023C34658"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "30340C10084E714023C34657"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "30340C10084E714023C34656"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "30340C10084E714023C34655"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "30340C10084E714023C34653"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "30340C10084E714023C3464D"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.connect_button.setText(_translate("MainWindow", "Kết nối"))
        self.reset_button.setText(_translate("MainWindow", "Đặt lại"))
        self.order_infor_table.setSortingEnabled(True)
        item = self.order_infor_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.order_infor_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.order_infor_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Đặt đơn của khách    "))
        item = self.order_infor_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mã hình thể"))
        item = self.order_infor_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hình thể xưởng"))
        item = self.order_infor_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tiểu chỉ lệnh    "))
        item = self.order_infor_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mã đơn hàng    "))
        item = self.order_infor_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Mã đặt đơn    "))
        item = self.order_infor_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Số lượng đặt hàng"))
        __sortingEnabled = self.order_infor_table.isSortingEnabled()
        self.order_infor_table.setSortingEnabled(False)
        item = self.order_infor_table.item(0, 0)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(0, 1)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(0, 2)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(0, 3)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(0, 4)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(0, 5)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(0, 6)
        item.setText(_translate("MainWindow", "100"))
        item = self.order_infor_table.item(1, 0)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(1, 1)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(1, 2)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(1, 3)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(1, 4)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(1, 5)
        item.setText(_translate("MainWindow", "TEST"))
        item = self.order_infor_table.item(1, 6)
        item.setText(_translate("MainWindow", "100"))
        self.order_infor_table.setSortingEnabled(__sortingEnabled)
        item = self.sizing_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cỡ giày"))
        item = self.sizing_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số lượng đặt đơn"))
        item = self.sizing_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tem đã phối"))
        item = self.sizing_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Đang sử dụng"))
        item = self.sizing_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Đã hủy"))
        item = self.sizing_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tem khách"))
        __sortingEnabled = self.sizing_table.isSortingEnabled()
        self.sizing_table.setSortingEnabled(False)
        item = self.sizing_table.item(0, 0)
        item.setText(_translate("MainWindow", "36"))
        item = self.sizing_table.item(0, 1)
        item.setText(_translate("MainWindow", "37"))
        item = self.sizing_table.item(0, 2)
        item.setText(_translate("MainWindow", "38"))
        item = self.sizing_table.item(1, 0)
        item.setText(_translate("MainWindow", "100"))
        item = self.sizing_table.item(1, 1)
        item.setText(_translate("MainWindow", "100"))
        item = self.sizing_table.item(1, 2)
        item.setText(_translate("MainWindow", "100"))
        item = self.sizing_table.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(2, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(3, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(4, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(4, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(5, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.sizing_table.item(5, 2)
        item.setText(_translate("MainWindow", "0"))
        self.sizing_table.setSortingEnabled(__sortingEnabled)
        self.manu_order_select.setItemText(0, _translate("MainWindow", "13A11C013"))
        self.manu_order_select.setItemText(1, _translate("MainWindow", "13A12B047"))
        self.actionSelect.setItemText(0, _translate("MainWindow", "Phối mới"))
        self.actionSelect.setItemText(1, _translate("MainWindow", "Phối bù"))
        self.size_select.setItemText(0, _translate("MainWindow", "36"))
        self.size_select.setItemText(1, _translate("MainWindow", "37"))
        self.size_select.setItemText(2, _translate("MainWindow", "38"))
        self.combine_type_select.setItemText(0, _translate("MainWindow", "Đại chỉ lệnh"))
        self.combine_type_select.setItemText(1, _translate("MainWindow", "Tiểu chỉ lệnh"))
        self.monoSeqSelect.setItemText(0, _translate("MainWindow", "001"))
        self.combine_proceed_button.setText(_translate("MainWindow", "Tiến hành phối"))
        self.label.setText(_translate("MainWindow", "Database IP"))
        self.label_3.setText(_translate("MainWindow", "UHF Reader TCP/IP"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.actionDatabase_connection.setText(_translate("MainWindow", "Database connection"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actioncollapse_sidebar.setText(_translate("MainWindow", "collapse_sidebar"))
        self.actioncollapse_sidebar.setShortcut(_translate("MainWindow", "Ctrl+B"))
